from pybricks.parameters import Port

ARM_PORT = Port.A
L_WHEEL_PORT = Port.B
R_WHEEL_PORT = Port.C
ULTRASONIC_PORT = Port.S1
WHEEL_DIAMETER = 55.5
AXLE_TRACK = 104
ASTEROID_DISTANCE = 500
ROTATION_COMPENSATION = 2
