from pybricks.parameters import Port

ARM_PORT = Port.C
L_WHEEL_PORT = Port.A
R_WHEEL_PORT = Port.D
HAMMER_PORT = Port.B
ULTRASONIC_PORT = Port.S4
WHEEL_DIAMETER = 55.5
AXLE_TRACK = 104
ASTEROID_DISTANCE = 500
ROTATION_COMPENSATION = 2
